services:
  mongodb:
    image: mongo:7
    container_name: photomind-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: photomind123
      MONGO_INITDB_DATABASE: photomind
    volumes:
      - photomind_mongo_data:/data/db

volumes:
  photomind_mongo_data:
